version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 6.11.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: npm
  directory: "/gh-badges"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: svgo
    versions:
    - 2.0.3
    - 2.1.0
    - 2.2.1
    - 2.2.2
